### GENERAL SETTINGS ###

# Site settings
title: poph.am
description: "My personal website, serving as a blog, resume, and portfolio."
analytics: UA-66507903-1
baseurl: "" #important: start with /
url: "http://poph.am"

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
permalink: /:categories/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#80c040" #"#F70031"
  primary_rgb: "128,192,64" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#404040" #"#33004D"
  link: "#80c040"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#c0c0c0"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/jpopham91
  - title: linkedin
    url: https://www.linkedin.com/in/jacobpopham
  - title: twitter
    url: https://twitter.com/jpopham91

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
#address:
#  - lines:
#    - Some Ave, 987,
#    - 23890, New York,
#    - United States.
#email: hello@solidtheme.com
#tel: +34 8493-4893


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
#members:
#  - name: Mark Webber
#    position: CEO
#    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
#    img: team01.jpg
#    social:
#      - title: envelope #use for email address
#        url: mailto:name@domain.com
#      - title: twitter
#        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: business insider
    img: business_insider.png
  - name: aol
    img: aol.png
  - name: dail mail
    img: daily_mail.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "A physicist turned data scientist, using a foundation in math, stats, and computer science to extract knowledge from 1s and 0s."
